#!/usr/bin/env bash
# Write gitignored .env files containing only secret keys (currently OPENAI_API_KEY)
# for Docker Compose interpolation and per-app local use. Run:
#   just secrets
#   (prompts securely if OPENAI_API_KEY is unset)
# Non-interactive: OPENAI_API_KEY=sk-... just secrets
#                  printf '%s' "$OPENAI_API_KEY" | just secrets
# shellcheck shell=bash

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

trim_space() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

ensure_openai_api_key() {
  if [[ -n "${OPENAI_API_KEY:-}" ]]; then
    OPENAI_API_KEY="$(trim_space "$OPENAI_API_KEY")"
    return 0
  fi

  if [[ -t 0 ]]; then
    read -r -s -p "OPENAI_API_KEY: " OPENAI_API_KEY
    echo
  else
    if ! IFS= read -r OPENAI_API_KEY; then
      echo "error: could not read OPENAI_API_KEY from stdin (pipe one line, or run from a terminal)." >&2
      exit 1
    fi
  fi

  OPENAI_API_KEY="$(trim_space "$OPENAI_API_KEY")"
}

write_secret_env() {
  local dest="$1"
  local tmp
  tmp="$(mktemp "${dest}.tmp.XXXXXX")"
  cat >"$tmp" <<EOF
# Secret-only env (generated by: just secrets). Do not commit.
OPENAI_API_KEY=${OPENAI_API_KEY}
EOF
  mv "$tmp" "$dest"
  chmod 600 "$dest"
  echo "wrote $dest"
}

ensure_openai_api_key

if [[ -z "$OPENAI_API_KEY" ]]; then
  echo "error: OPENAI_API_KEY is empty." >&2
  exit 1
fi

if [[ "$OPENAI_API_KEY" == *$'\n'* ]]; then
  echo "error: OPENAI_API_KEY must be a single-line value." >&2
  exit 1
fi

write_secret_env "$ROOT/api-rust/.env"
write_secret_env "$ROOT/api-node/.env"
